### ISSUE TITLE
Fix events questionnaires api

### ISSUE THREAD

**Issue by darleet** [bmstu-itstech/rs-front#15]
Ко всем мероприятиям приходит один набор анкет, нужно пофиксить, у каждого меро уникальный набор анкет. Мб там вообще запроса не приходит, хз, надо глянуть. В любом случае поведение некорректное, надо фиксить

**Comment by coma8765** [comment]
в процессе

**Comment by coma8765** [comment]
бек так возвращает @darleet 

<img width="718" alt="Снимок экрана 2024-09-30 в 14 11 53" src="https://github.com/user-attachments/assets/685d400b-cc57-45e2-b48e-6625510680a5">
